version: '3.8'

services:
  opensearch-node:
    image: opensearchproject/opensearch:2.11.1
    container_name: opensearch-node
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5

  webapp:
    build: .
    container_name: webapp
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      opensearch-node:
        condition: service_healthy

volumes:
  opensearch-data: